// Writes firestore.local.rules: firestore.rules with the host@example.com placeholder replaced by
// VITE_ADMIN_EMAIL from .env, so the real admin email never has to be committed.
import { readFileSync, writeFileSync } from 'node:fs';
import { loadEnv } from 'vite';

const PLACEHOLDER = "'host@example.com'";
const adminEmail = (loadEnv('production', process.cwd(), 'VITE_').VITE_ADMIN_EMAIL || '').trim().toLowerCase();

if (!/^[^\s@']+@[^\s@']+\.[^\s@']+$/.test(adminEmail)) {
  console.error('VITE_ADMIN_EMAIL in .env is missing or invalid; cannot build firestore.local.rules.');
  process.exit(1);
}

const rules = readFileSync('firestore.rules', 'utf8');
if (!rules.includes(PLACEHOLDER)) {
  console.error(`firestore.rules no longer contains the ${PLACEHOLDER} placeholder.`);
  process.exit(1);
}

writeFileSync(
  'firestore.local.rules',
  '// GENERATED by scripts/build-rules.mjs from firestore.rules. Edit firestore.rules instead.\n' +
    rules.replaceAll(PLACEHOLDER, `'${adminEmail}'`)
);
console.log('Wrote firestore.local.rules for the admin account in .env.');
